### PR TITLE
Polish translation 

### PR DESCRIPTION
**Pull request by orzels**
Hello.
Here is a polish translation from english json template file. Consistent with Mac OS X language style

Best
Orzels
[pl.json.zip](https://github.com/yakyak/yakyak/files/822675/pl.json.zip)

### CODE REVIEW

**Comment by averissimo** [comment]
@orzels there are 2 problems with the translation you submitted:

1. Found that your file had strange characters „ and ” -- which are not accepted in the json format
1. Language string should have "Language" in parenthesis, this helps in case of an user error when setting the language -- "language": "Język (Language)"

I corrected that and is available here: http://bit.ly/2npL8fa

-------------------

__Regarding the pull request itself:__

Normally pull requests are performed when you fork _(create a clone)_ of this repository, then make the changes and request the changes

  - This allows to track the changes that are proposed
  - But this is not straightforward when you start developing in github, I still remember the confusion on the first time I did it :)

Do you think you can submit following Github guidelines? 

- [Fork a repo](https://help.github.com/articles/fork-a-repo/)
- [Creating a pull request from a fork](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

Alternatively, I can do it myself.

**Comment by averissimo** [comment]
@orzels there is already a Polish translation by @aPoCoMiLogin 

there are slight changes between the two. (one example below)

image

Can you guys work together to find which strings can be improved?

p.s. in the mean time I'll update the readme with all languages, including Polish.

**Comment by aPoCoMiLogin** [comment]
Well that different part from @orzels is wrong, like out of google translate.

**Comment by averissimo** [comment]
I'm closing the pull request and initiating other with the actual code (instead of a zip)

I cannot evaluate them so I'm not pushing for any given change. Translations by native or fluent in Polski are always preferred over google translate.

New pull request at #630

**Comment by orzels** [comment]
It was native. But please keep Filip way, I believe he do it better. 
Pozdrawiam z Wrocławia / Best Regards from Wroclaw 

Piotr

W dniu 17.03.2017, 15:02, o 15:02, użytkownik Filip Szczechowiak <notifications@github.com> napisał:

**Comment by aPoCoMiLogin** [comment]
Just checked all differences, and there are some areas that can be taken from @orzels and some that I did before. I'll sum it up tonigth.

Cheers from wroclaw too ;)

**Comment by orzels** [comment]
Please consider that some of my translations is taken from Mac OS environment. And for Windows/Linux users can be weird, eg Preferences - Preferencje vs Ustawienia. 

If Filip can mix our work for best user feel, that will be best solution :) 

Piotr


W dniu 17.03.2017, 15:53, o 15:53, użytkownik Filip Szczechowiak <notifications@github.com> napisał:

**Comment by averissimo** [comment]
@orzels cool!! he has added a new comment exactly on the same note here

https://github.com/yakyak/yakyak/pull/630#issuecomment-287376020

**Pull request closed without merging**
