### PR TITLE
Workaround for KDE not scaling electron tray images properly

### LINKED ISSUE #788: Bad icon size system tray KDE
Hi,

    There is a problem with the system tray icon size, which looks huge. This is on KDE desktop (plasma desktop).

KDE Frameworks: 5.39.0  
KDE Plasma: 5.11.1
Distro: KDE Neon (Ubuntu 16.04 based)

yakyak_systray_icon_kde

### LINKED ISSUE #928: Directions to bad icon info?
Sorry for just putting it out here i searched for a good while for an issue i saw back a while ago. Could someone direct me to a fix for bad tray icon on Linux  64 bit Fedora here. Looks lovely as this. :) Thanks
yakyak

### PR DESCRIPTION
**Pull request by sosguthorpe**
Fixes #788
Fixes #928

### CODE REVIEW

**Comment by dos1** [comment]
It's actually Chromium that's breaking the icon. I've submited a patchset that fixes this issue: https://chromium-review.googlesource.com/c/chromium/src/+/1173235

**Comment by averissimo** [comment]
should this be merged? @sosguthorpe 

We are now using a very updated version of electron v3.0.x that should have @dos1 patch

**Comment by sosguthorpe** [comment]
I have just tried the current 1.5.2 release and the issue with bad icon size is still present for me in KDE. Should the electron dependency within that version be sufficient for this to be fixed?
I tried both the `.deb` and then the `.tar.gz` packages. And both revert the image back to the over-zoomed one for me.

**Comment by averissimo** [comment]
you forgot to add the files to gulpfile and follow same naming convention in icons folder

I've corrected and scheduled travis to rebuild the v1.5.2 binaries

**Comment by dos1** [comment]
BTW: You should revert it once Electron gets the version of Chromium where it's fixed, as it's lowering the quality of the icon for bigger panels or hidpi screens.

**Comment by averissimo** [comment]
At which chromium version was it merged? just to keep a look-out for electron's release notes

**Comment by sosguthorpe** [comment]
@averissimo Just checked the change logs and it's in the current dev V71 branch but not stable V70 so looks like when 71 is released we could potentially reverse this.

**Comment by averissimo** [comment]
Cool! I'd appreciate if you could keep an eye on when we could revert it.

**Pull request merged**
