### PR TITLE
Ctrl and enter to send

### PR DESCRIPTION
**Pull request by easauceda**

### CODE REVIEW

**Comment by PMiner** [comment]
Yay! Thanks!

**Comment by easauceda** [comment]
No problem!

I noticed that just enabling ctrl + enter would disallow from using it to add line breaks to your message, so I think this strikes a good balance for people who prefer one behavior over another.

**Comment by PMiner** [comment]
Perhaps shift+enter for break?

**Comment by easauceda** [comment]
can't believe I missed that...good catch! really makes it a lot less complicated

**Comment by davibe** [comment]
So basically you want to be able to do ctrl + enter because when you copy-paste and send stuff you forget to release ctrl ? Am i getting this right ?

**Comment by davibe** [comment]
So basically you are adding a toggle in the menuitem + adding a new shortcut (shift+enter) just because you forget to release ctrl before hitting enter. I am not sure about this, hmm..

**Comment by conceptualspace** [comment]
why not just be consistent with hangouts? thus shift+enter = break, and enter/ctrl+enter = send

**Pull request closed without merging**
