### PR TITLE
Add Flatpak build for Linux packaging

### PR DESCRIPTION
**Pull request by Celti**
YakYak currently has no distribution-independent Linux packages
available; only plain tarballs, which are not ideal. Meanwhile, Flatpak
packages for YakYak have been requested twice, in #387 and #507. This
change brings [`electron-installer-flatpak`][1] into the dev-dependencies
and adds `deploy:linux:flatpak` to the existing package types.

Actually building the flatpak requires the host system to have
[`flatpak-builder`][2] and v1.6 of the `org.freedesktop.Platform`
Flatpak runtime and SDK installed.

[1]: https://github.com/endlessm/electron-installer-flatpak
[2]: https://github.com/flatpak/flatpak-builder

### CODE REVIEW

**Comment by averissimo** [comment]
Great!!

I'm having an error when running the script:

image

Versions

image

*TODO: (probably in a separate pull request)*

* add to travis-ci pipeline so it can be built and deployed with every new release (and pre-release)

**Comment by averissimo** [comment]
Am I missing any dependency?

Using ubuntu 18.04 and flatpak versions are in the screenshot above *(installed from apt)*

**Comment by Celti** [comment]
You need the 1.6 version of the SDK installed as well:
```
flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak --user install flathub org.freedesktop.Sdk/i386/1.6 org.freedesktop.Sdk/x86_64/1.6
```

**Comment by averissimo** [comment]
Also had to run `flatpak --user install flathub org.freedesktop.Platform`

Below are the commands.

I'm trying to integrate this on the travis-CI system that builds everything, but it requires an operating system that is not yet publicly released (*xenial*) (see https://github.com/travis-ci/travis-ci/issues/7260 )

Depending on whether it builds I'll ask you to merge the `.travis.yml` in `Celti-flatpak` branch before accepting the pull request

```
apt install flatpak-builder flatpack
flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak --user install flathub org.freedesktop.Platform
flatpak --user install flathub org.freedesktop.Sdk/i386/1.6 org.freedesktop.Sdk/x86_64/1.6
npm run deploy:linux-x64:flatpak
```

**Comment by Celti** [comment]
Sounds like a plan!

To make sure the Travis environment is up-to-date with Flatpak you may want to use the PPA, if you can (again still requiring 16.04 minimally):
```
add-apt-repository ppa:alexlarsson/flatpak
apt update
apt install flatpak-builder flatpak
```

For clarity, optimal versions, coverage of all bases, and avoiding failure, the flatpak commands should be as follows:
```
flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
# For x64:
flatpak --user install flathub org.freedesktop.Sdk/x86_64/1.6
flatpak --user install flathub org.freedesktop.Platform/x86_64/1.6
npm run deploy:linux-x64:flatpak
# for ia32
flatpak --user install flathub org.freedesktop.Sdk/i386/1.6
flatpak --user install flathub org.freedesktop.Platform/i386/1.6
npm run deploy:linux-ia32:flatpak
```

**Comment by averissimo** [comment]
Build is failing: https://travis-ci.org/averissimo/yakyak/jobs/322345971

It uses xenial and the ppa as you noted :) .. but xenial is not "released" yet, it's been quietly added and it takes some time for each job to run

Latest job is on queue and has much more debugging, let's see what comes from it: https://travis-ci.org/averissimo/yakyak/jobs/322382866

If you already know what is wrong, let me know :)

Below is the instructions given to build support for flatpak in Xenial

```
  - sudo add-apt-repository ppa:alexlarsson/flatpak -y
  - sudo apt update
  - sudo apt install flatpak-builder flatpak
  - flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  # 64-bits
  - flatpak --user install flathub org.freedesktop.Sdk/x86_64/1.6
  - flatpak --user install flathub org.freedesktop.Platform/x86_64/1.6
  # 32-bits
  - flatpak --user install flathub org.freedesktop.Sdk/i386/1.6
  - flatpak --user install flathub org.freedesktop.Platform/i386/1.6
  # actuall building of the binaries
  - npm run -loglevel silly deploy:linux-x86:flatpak
```

**Comment by Celti** [comment]
Looks like the "silly" debug level run failed because it can't find the `deploy:linux-x64:nodep` deploy script... and I can't for the life of me figure out why *that* is. Taking a look at the run that failed on 'flatpak' now...

Can we try `export DEBUG='electron-flatpak,electron-installer-flatpak,flatpak-bundler'` in travis.yml?

**Comment by Celti** [comment]
Alright, looking at the latest build, passing `-loglevel silly` isn't getting passed through to the right software. Definitely need to try modifying the `DEBUG` export, I think.

**Comment by averissimo** [comment]
Missing run target for flatpak 32-bits -_-

x86 run smoothly, which is awesome and next one is still on target.

This next one should run without problems, I'll come back to see later today :)

My only concern is with how long it takes for each build to run in xenial, seems like a lot less computational power is being used for these builds using the still not announced xenial.

Anyway, it shouldn't be a problem.

**Comment by averissimo** [comment]
Sent a PR with the code from Celti-flatpak branch to your fork,  I'm not really sure on the best procedure, but new code should always go through a pull request... 

So I guess this is the best way to do it :)

**Comment by Celti** [comment]
Hey, that works for me! Merged, and we'll let the final travis build go through here.

**Comment by averissimo** [comment]
travis only runs the deploy scripts for tags, and not for commits nor pull requests

**Comment by averissimo** [comment]
It builds nicely and v1.5.0 already has the flatpak packages.

*One question:* is there a naming convention for flatpak packages? I would prefer something like yakyak-X.Y.Z-linux-arch.flatpak

**Comment by DanaMW** [comment]
Did you in tend to leave the version number 1.4.4 under the 1.5.0 pre release a few minutes ago?

**Comment by averissimo** [comment]
oh crap! thanks!

**Comment by DanaMW** [comment]
Yes sir. Welcome

**Comment by averissimo** [comment]
@Celti flatpak is not building with code in master

```
  flatpak-bundler 2> error: io.atom.electron.BaseApp/x86_64/master not installed
  flatpak-bundler  +58ms
  flatpak-bundler 2> Failed to init: Unable to find app io.atom.electron.BaseApp version master
```

**Pull request merged**
