### PR TITLE
subtle links to the install hints

### PR DESCRIPTION
**Pull request by l00mi**

### CODE REVIEW

**Comment by davibe** [comment]
I'd rather link to the binaries instead of the wiki explaining how to build. It's what we did in the past but since it's boring to always update links i stopped doing it.

**Comment by l00mi** [comment]
My intend is to make it visible how you can install YakYak with Homebrew on macOs which is a really convenient way to stay up-to-date.

**Comment by davibe** [comment]
It's the subtle part i think i don't like. It has to be clear. Does this look acceptable to you ?

**Comment by l00mi** [comment]
Perfect! cheers

**Pull request merged**
