### PR TITLE
normalize coffee a smidge (pre decaf)

### PR DESCRIPTION
**Pull request by refack**
These tiny changes/improvements allow using `[decaffeinate](https://github.com/decaffeinate/decaffeinate)` to get pretty-pretty ES6 (node 4 compliant) output

### CODE REVIEW

**Comment by davibe** [comment]
why do you decaffeinate yakyak ?

**Comment by refack** [comment]
I'm enjoying playing with compilers, but I'd take the challenge, and make your CoffeeScript compile as is 😉

**Comment by refack** [comment]
[OT] why do you use the two proc approach (dispatcher & client)?

**Comment by davibe** [comment]
I was not against the PR. Just wanted to undestand.

It's electron that separates those two concepts. I think at first we did it so that everything could survive even without any window open. Later we discovered we could just hide the window.

 I am not a big fan of this separation either and i think we could try to move yakyak from the 'server' process to the 'renderer' one. I am not sure what would break though. Maybe the renderer process does not have 100% of node-apis. I don't remember exactly

**Comment by refack** [comment]
Got it (RE: separation)
As for the PR, fixing `decaffeinate` to deal with real-world-in-the-wild code is better after all (plus `hangupsjs` is way more challenging 😜)

**Pull request closed without merging**
