### PR TITLE
Update url regex expression #573

### PR DESCRIPTION
**Pull request by averissimo**
allowing links in parenthesis and also open recognized links without a protocol `www.google.com`

### CODE REVIEW

**Comment by smkent** [comment]
Links without a protocol (ex. `www.github.com`) and the test case you listed in #573 with a URL in parentheses (`ada (http://www.google.com)`) seems to work. However, links in parentheses with a URI component still are linked incorrectly, e.g. "([http://www.example.com/bogus-url/)](http://www.example.com/bogus-url/\))"

**Comment by davibe** [comment]
so i wait before merging

**Comment by averissimo** [comment]
Upstream issue: https://github.com/kevva/url-regex/issues/34

Let's see what they say :)

**Comment by davibe** [comment]
did they say anything ?

**Comment by averissimo** [comment]
seems like there is already a pull request, but it's waiting to get merged :)

**Comment by davibe** [comment]
if it does not get merged you can create your own fork of that lib and we can use that as a dependency :)

**Comment by averissimo** [comment]
seems right!

**Comment by davibe** [comment]
@averissimo what's the status on this ?

**Comment by averissimo** [comment]
I was just revisiting this issue and it is not as straightforward as one would think.

There is definitely some cases that we can avoid, such as one or more parenthesis in the end of the url, but even then it might fail 

Test in hangouts web (not yakyak)

image

Test in github

(works http://sapo.pt/)
(works http://sapo.pt/something)
(works http://sapo.pt/aa(123)aa)

**Comment by averissimo** [comment]
I think we can try and use google's method, remove all parenthesis in the end, unless there is an opening parenthesis in the path

**Comment by averissimo** [comment]
I forked the project and managed to add the requirements to the regular expression.

Runs all previous tests and [added some](https://github.com/averissimo/url-regex/blob/master/test.js#L4-L20) based on past 2 comments in this thread :)

@davibe should I create an actual npm module or can it be installed from github in `package.json`

**Comment by davibe** [comment]
For yakyak just referring to the fork is ok. For the sake of the community using url-regexp i don't know. Npm modules are owned by each publisher so you would publish a duplicate.. maybe you would need to change its name.. messy.

I'll just merge this

**Pull request merged**
