### PR TITLE
Polish translation  by @orzels

### PR DESCRIPTION
**Pull request by averissimo**
Continue the discussion in #617

@orzels @aPoCoMiLogin

### CODE REVIEW

**Comment by aPoCoMiLogin** [comment]
Just checked all differences, and there are some areas that can be taken from @orzels and some that I did before. I'll sum it up tonigth.

Cheers from wroclaw too ;)

**Comment by averissimo** [comment]
Yay!!

If you can, do it on a branch based on this one and I'll merge it.. this way we can focus the entire conversation here.

__Additional string to be added__ : `"startup": "Open on Startup"`

It is under menu.help.about

**Comment by aPoCoMiLogin** [comment]
Sorry for my delay on it.. @averissimo Here you can pull combined changes with translation of additional string: https://github.com/aPoCoMiLogin/yakyak/tree/i18n-polish-orzels

@orzels check if you agree with those changes: https://github.com/aPoCoMiLogin/yakyak/commit/31bd6a5f845a3098d05537f85ed04143ff984f54?diff=split

**Comment by aPoCoMiLogin** [comment]
@orzels also just changed this one: https://github.com/aPoCoMiLogin/yakyak/commit/e478d4f35cbced5a73db5003a7d794b09696a286?diff=split

**Comment by averissimo** [comment]
@orzels ?

I'll merge it around monday 3rd of April if no feedback :)

**Pull request merged**
