### PR TITLE
Minimal convlist option, unread counter style.

### PR DESCRIPTION
**Pull request by arnriu**
#349

### CODE REVIEW

**Comment by arnriu** [comment]
capture d ecran 2016-08-25 a 16 09 21

**Comment by davibe** [comment]
@arnriu i believe for some user like me "minimal" would be just the text (contact name). Can you think of a better menu arrangement/name ?

Also. Is "animated thumbnails" compatible with "minimal" mode ?

**Comment by arnriu** [comment]
@davibe I know, the text isn't perfect, I was hoping for some help, since english is not my native language... ;)
I tried a new menu arrangement, let me know what you think about it.

And yes, animated thumbnails are compatible.

**Comment by arnriu** [comment]
capture d ecran 2016-08-29 a 17 08 20

**Comment by davibe** [comment]
Since it's all "show" we could put "show animated thumbnails". I like this version better. I am not native english either, but who is :)
I will test it soon, i hope

**Comment by randymorris** [comment]
I haven't had a chance to test this, but does unchecking the first option disable the other two?  I would think that it should since only thumbnails and animated thumbnails sort of contradict not showing any thumbnails.

**Comment by arnriu** [comment]
@randymorris no, if you uncheck first option, second and third options are still available:
- if you check second option while first is unchecked, it will check it. If you uncheck first option while second is checked, it will uncheck it.
- animated thumbs are also used in messages, so it is not dependent on conversation list thumbs.

Maybe the text are wrong? I'm open to any suggestions :)

**Comment by randymorris** [comment]
Ah, I forgot about the message pane.  Forgive me.

**Comment by arnriu** [comment]
capture d ecran 2016-08-30 a 15 57 15

**Pull request merged**
