### PR TITLE
Fixes #1234.

### LINKED ISSUE #1234: Crash at launch
When launching 1.5.9, it often crashes with the following error:
```
{
  msg: "Uncaught TypeError: Cannot read property 'length' of undefined",
  url: '/opt/yakyak/resources/app/ui/models/conv.js',
  lineNo: 42,
  columnNo: 34,
  error: TypeError: Cannot read property 'length' of undefined
      at /opt/yakyak/resources/app/ui/models/conv.js:42:34
      at add (/opt/yakyak/resources/app/ui/models/conv.js:49:9)
      at Object._initFromConvStates (/opt/yakyak/resources/app/ui/models/conv.js:522:17)
      at Object.init (/opt/yakyak/resources/app/ui/dispatcher.js:54:10)
      at doAction (/opt/yakyak/resources/app/node_modules/trifl/lib/action.js:45:68)
      at action (/opt/yakyak/resources/app/node_modules/trifl/lib/action.js:21:12)
      at Object.init (/opt/yakyak/resources/app/ui/dispatcher.js:39:14)
      at file:///opt/yakyak/resources/app/ui/app.js:207:23
      at EventEmitter.<anonymous> (file:///opt/yakyak/resources/app/ui/app.js:105:16)
      at EventEmitter.emit (events.js:223:5)
}
```

It does not seem to happen everytime.

### PR DESCRIPTION
**Pull request by jellisii**
See https://github.com/yakyak/yakyak/issues/1234#issuecomment-697462483

### CODE REVIEW

**Comment by eacmen** [comment]
anyone have a build with this patch? this bug is annoying. I wish travis would build and publish the PRs as well.

**Comment by cwells** [comment]
> anyone have a build with this patch? this bug is annoying. I wish travis would build and publish the PRs as well.

If you're willing to build from source, it's quite straightforward to apply the patch:

```
git clone https://github.com/yakyak/yakyak.git
cd yakyak/
git fetch origin pull/1245/head:patch-1245
npm install
npm run gulp
npm run deploy:linux-x64:rpm # build RPM for x64 linux
```

**Comment by HomerSp** [comment]
I've had the same issue, and this fix/workaround looks good to me. @averissimo Can we get this merged, please?

**Review by jeffbyrnes — APPROVED** [review]
Works well for me on macOS 10.15.7

**Comment by jeffbyrnes** [comment]
@jellisii also, if you update the description to say “fixes #1234”, this will auto-close that issue when this is merged 🙂

**Comment by jjs10** [comment]
I was having the same issue on my Fedora Linux computer. I made the same change as this fix and it works for me now. After doing a fresh install of 1.5.9 I manually edited the /opt/yakyak/resources/app/ui/models/conv.js file by changing line 36 to be: 

`({conversation, event = []} = conv);`

**Comment by eacmen** [comment]
For those that don't want to install npm, I forked the repo, applied this patch and had Travis build the releases:

https://github.com/eacmen/yakyak/releases/tag/v1.5.11-eacmen

Sad to see this project seems to be abandoned. Appreciate all the hard work but if critical PRs like this need to get merged and released as beta in a more timely fashion.

**Comment by jeffbyrnes** [comment]
@eacmen calling a project “abandoned” when an issue is barely 3 weeks old, and the last release is from 4 months ago, is a bit much.

@averissimo maintains this on their own time, so “timely” is whatever they feel able to provide. None of us are paying them for their effort, so that criticism is both unwarranted & unwelcome.

**Comment by eacmen** [comment]
> @eacmen calling a project “abandoned” when an issue is barely 3 weeks old, and the last release is from 4 months ago, is a bit much.
> 
> 
> 
> @averissimo maintains this on their own time, so “timely” is whatever they feel able to provide. None of us are paying them for their effort, so that criticism is both unwarranted & unwelcome.

Meant no disrespect to the maintainer. I appreciate the time and effort they've put in. 

My argument is this is a breaking issue, users can't log in at all and has no workaround other than editing source code. Normal everyday users aren't developers and need an installable package to use this software.

We're in a unique position where we have the means to fix these issues ourselves. Let's not forget about "normal" folks.

**Comment by buelowp** [comment]
Until there is a new snap release, is there a way to fix this in the snap? If not, that's fine, I can wait, just a new user that would like to use it.

**Comment by blondehouse** [comment]
Hi!

I'm having trouble finding the pathway to get to the file to change it. Does someone mind writing a step by step as to how to change this file and where to find it? I'm new to all of this and want to make sure i get it right.

Thank you!

**Comment by sriharshachilakapati** [comment]
@blondehouse Please redownload the app from the releases. It is updated and works now.

**Pull request merged**
