### PR TITLE
Upgrade electron dependencies to 2.0.2 issue #914

### PR DESCRIPTION
**Pull request by Dodenis**
Fix issue #914 Tray icon for ubuntu 18.04

### CODE REVIEW

**Comment by ghisvail** [comment]
Might be worth upgrading to [electron v2.0.8](https://github.com/electron/electron/releases/tag/v2.0.8), which is the latest release of the 2.x series at this time.

Electron v.1.7.x is definitely old. At least consider the upgrade to [v1.8.x](https://github.com/electron/electron/releases/tag/v1.8.8) which offers a smoother upgrade path towards 2.x or 3.x later.

**Comment by averissimo** [comment]
@Dodenis have you been running with this fix?

@ghisvail can you help test it out?

I've stopped using hangouts and yakyak so I cannot test right now

**Comment by averissimo** [comment]
@Dodenis I've went a bit further and updated to 3.0.2

There seems to be a problem with `electron-packager`, but otherwise yakyak seems to be working ok

Check out the branch: [Dodenis-upgrade-electron](https://github.com/yakyak/yakyak/tree/Dodenis-upgrade-electron)

**Comment by averissimo** [comment]
This branch also updates other modules

**Comment by averissimo** [comment]
Closing in favor of the merged branch. check pre-release v1.5.2

**Pull request closed without merging**
