### PR TITLE
npm start | npm run dev | no_zip packaging | electron-prebuilt deprecated

### PR DESCRIPTION
**Pull request by averissimo**
- electron-prebuilt package is deprecated 
- checks if NO_ZIP environment variable is set to skip zip creation in packaging
- adds `npm start` (no run in the middle, compiles and starts) and `npm run dev` targets (inspired by electron demo: https://github.com/electron/electron-api-demos )

### CODE REVIEW

**Comment by averissimo** [comment]
the lint tab inside the devtron tab when running `npm run dev` has some nice tips on stuff we should eventually do

marked in red:

image

**Comment by averissimo** [comment]
Added methods to catch these events in https://github.com/yakyak/yakyak/pull/500/commits/553c76e3aaaf5c7abbc8efbad602aa446bd1a5dd

**Comment by averissimo** [comment]
@davibe the .travis file has as requirements node_js `0.12`

Ca we update this requirement to v6 or v4 I believe the travis check failed on this one because of this

**Comment by davibe** [comment]
sure..

**Pull request merged**
