### PR TITLE
adds maximum of five visible lines to limit text area

### LINKED ISSUE #242: Window freaks out if long message is taller than window height
Not a big deal, but thought I would add it to the list for you. 

If you write a message taller than the height of the window (mine is full height), and send it. Both panels of the app (contacts and message) freak out.

Restarting the whole app fixes it and it can display the tall message properly.

### LINKED ISSUE #252: Hide archived chats

### PR DESCRIPTION
**Pull request by averissimo**
closes #242

### CODE REVIEW

**Comment by KusioST** [comment]
Hello. Sorry for delay. Work, work, never end. How can I help You with this?

**Comment by averissimo** [comment]
@KusioST can you test this out? if can't build from source let me know and I'll build a binary

**Comment by davibe** [comment]
tested on osx, seems fine

**Comment by KusioST** [comment]
If You give me a build I will test it.

**Comment by KusioST** [comment]
I test version:
https://github.com/yakyak/yakyak/releases/tag/v1.4.4-position

And this is result:
01. After paste 50 new lines:
yakyak - 01 after paste 50 new lines
02. Afted delete this lines
yakyak - 02 afted delete this lines

**Comment by averissimo** [comment]
Although already merged the prereleases were not updated.

The ones with suffixes are tests we perform, next time we need to make it a little bit more obvious (our bad!)

We are now building a new prerelease with this merge, in 10-15 minutes it will be available to download.

Thanks!!

**Comment by KusioST** [comment]
OK. If You will need new test, just let me know.

**Pull request merged**
