### PR TITLE
Fix #1087 "Couldn't sign into Google"

### LINKED ISSUE #1087: Google Couldn't sign you in Yakyak
The project run correctly but when i tried to sign in show this problem:

> You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.
> Try using a different browser.

imagen

### PR DESCRIPTION
**Pull request by signedbit**
Fix for #1087 spoofs user-agent. Credit to https://github.com/yakyak/yakyak/issues/1087#issuecomment-565170640

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@averissimo would you please merge this in? It fixes a bug that’s a blocker to logging in.

**Comment by averissimo** [comment]
I'm going through more pull requests, anything in particular I should look at? @jeffbyrnes 

Sorry for neglecting yakyak, but we need someone to active maintain it

**Comment by jeffbyrnes** [comment]
@averissimo don’t think so, but maybe some of the Greenkeeper-labeled PRs?

**Comment by jeffbyrnes** [comment]
And it’s all good! Glad to see you here at all merging things :) Happy to help out a bit if you like.

**Pull request merged**
