### PR TITLE
I18n multilanguage

### PR DESCRIPTION
**Pull request by averissimo**
Initial multi-language support [#332]

It already has support for:

- Spanish
- Portuguese
- French

English default is written directly in code by `i18n.__('som.key.path:Default English string')`

New translations should be based on `en.json.template`

Heads up: this will probably conflict with #522

### CODE REVIEW

**Comment by averissimo** [comment]
- Conflicts resolved
- Adds German language

**Comment by aPoCoMiLogin** [comment]
I think that is worth mention in `README.md` in **Structure** section about locales location.

**Comment by averissimo** [comment]
@aPoCoMiLogin how so?

a howto on how to translate to new language?

**Comment by aPoCoMiLogin** [comment]
I mean to add info about `/src/locales` location, to [https://github.com/yakyak/yakyak#structure](structure) section, just for consistency ;)

**Pull request merged**
