### PR TITLE
Add wine warning when building windows binaries

### PR DESCRIPTION
**Pull request by averissimo**
When building in Linux and Mac OS X it checks if it has wine installed and print a warning to install

If wine is installed it gives a notice

image

### CODE REVIEW

**Comment by nerijus** [comment]
I am not sure if 32 bits specifically is needed, as I was able to use 64 bit prefix wine. But if rcedit.exe is 32 bit app, then technically yes, wine which is able to run 32 bit apps is needed.

**Comment by averissimo** [comment]
**can you build the 32bit binary with 64bit wine?**

do you think 32bit reference should be removed and just say wine?

or rephrase to something like:

```
... please be sure to have wine installed and configured.

(if wine still fails, try using both wine 32 and 64 bits architecture)
```

**Comment by nerijus** [comment]
Yes, just wine is OK.
"(if wine still fails, try using both wine 32 and 64 bits architecture)"
No, for me 64 bit prefix helped because my 32 prefix was wrecked. So just wine is OK, or something like "try with a new/empty prefix".

**Comment by nerijus** [comment]
> can you build the 32bit binary with 64bit wine?
I built 32 bit binary with 64 bit wine prefix, but I am not sure if wine exe 32 or 64 bit was used. But prefix was 64 bit.

**Comment by averissimo** [comment]
updated

**Comment by nerijus** [comment]
"If problem persist try a different wine prefix" should be "If problem persists try a different wine prefix".

**Comment by davibe** [comment]
Is it yakyak job to detect wine absence and give warnings ? shouldn't it be a job of electron-packager or one of its dependencies ?

**Comment by averissimo** [comment]
true, I'll open a issue there instead

**Comment by averissimo** [comment]
https://github.com/electron-userland/electron-packager/issues/357 open issue and currently being discussed

**Pull request closed without merging**
