### PR TITLE
New skin and some new features

### PR DESCRIPTION
**Pull request by ariu**
New skin, color schemes, timestamp and last message in conv list, presence status, material icons font, roboto font, new (temporary ?) icon, and some more fixes and improvements.

https://github.com/yakyak/yakyak/issues/147 https://github.com/yakyak/yakyak/issues/155 https://github.com/yakyak/yakyak/issues/103 https://github.com/yakyak/yakyak/issues/152 https://github.com/yakyak/yakyak/issues/137 https://github.com/yakyak/yakyak/issues/21 https://github.com/yakyak/yakyak/pull/156

see: https://github.com/ariu/yakyak/releases

### CODE REVIEW

**Comment by algesten** [comment]
wow. tons of stuff here :+1: can we perhaps just rebase off master?

**Comment by algesten** [comment]
hm. ok. perhaps you clash because of the theme switch i merged #146 . can your work be made to work in tandem with that?

**Comment by ariu** [comment]
I have implemented color themes too, but in a slightly different way. It would be complicated to get @mrohr system, because I changed some html for my skin, (removed elements, added new ones, ...) and I have a slightly different approach for color variables. I think mine is less complex and easier to use.

While @mrohr uses less variables and mixins, and generate css theme files, I use css variables instead ( https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables ) available in chrome 49, to define colors for the whole document on <html> root element. If I want te create a new color theme, I just add a new class to <html> element and override css variables I want to override. I can, with this class and css cascade system, override a specific element color too. And that's all, only some css magic. No less mixins, no new css file. See [this less file](https://github.com/ariu/yakyak/blob/483fe38e56a08475fb29387a34adc924e2330d8c/src/ui/css/yakyak/colors.less).

In yakyak menu, I simply add / remove css classes when switching from a theme color to another. see [here](https://github.com/ariu/yakyak/blob/master/src/ui/views/menu.coffee#L43) , [here](https://github.com/ariu/yakyak/blob/master/src/ui/dispatcher.coffee#L333) , and [here](https://github.com/ariu/yakyak/blob/master/src/ui/models/viewstate.coffee#L133).

I tried to create a dark theme using @mrohr colors from his theme, and added a new commit with it. We can still tweak it, maybe @mrohr will do it? :)

Since I changed a lot or stuff, I'm suggesting revert to https://github.com/yakyak/yakyak/commit/9c678ebfbd35dbe013772d41f9feda7c93123ace , merge this pull, then update icon, deps, and other stuff you did.

vanilla yakyak light theme:

capture-d ecran-2016-04-07-a-04 04 23


vanilla yakyak dark theme from https://github.com/yakyak/yakyak/pull/146 :

capture-d ecran-2016-04-07-a-04 03 46


new skin yakyak default theme:

capture-d ecran-2016-04-07-a-04 03 28


new skin yakyak dark theme:

capture-d ecran-2016-04-07-a-04 03 41

**Comment by algesten** [comment]
Okay. I have backed out @mrohr changes, so perhaps you can rebase off master now? A couple of things regarding your changes:

1. your css variable names should change so that they describe function instead of colour. i.e. instead of `--gray` it should be `--panelbackground`.
2. regarding your new default designs a couple of thoughts
  * we've deliberately distanced ourselves from google's styles, since we don't know whether a reversed engineered chat protocol would sit well. taking on their brand identity as default is not a great idea.
  * google's brand identity sucks :) ... the design philosophy of yakyak is more in line with apple's messages. particularly in your changes i would ask myself "what does the top bar do?" and my biggest bug bear "why does it need to say Conversations" always at the top?

**Comment by matthewdias** [comment]
about google's "brand identity":
- I wouldn't call material design a brand identity. It's more like a ui framework, that they've made with the hopes that it will be used by others, so I don't see "taking" it as an issue
- as far as the top bar, you're right, but this is mostly because google's and apple's designs kind of clash. If you want to keep the material themes as options, I'd recommend doing away with one of the bars. Either the material one, or the os x one. (maybe use something like https://github.com/kapetan/titlebar to add the window controls to the material bar)

**Comment by ariu** [comment]
@algesten

I did rebase / merge from current yakyak master: https://github.com/ariu/yakyak/commits/master

1. I see your point. Mine was instead: I want to replace all green in page, regardless of what element it is. For exemple, all default green as to go blue. So I change green variable to blue, and voila, every green element becomes blue. Perhaps, we could have general variables, and specific variables that make use of general variables like bootstrap does.
exemple:
// general
--blue: #0000FF;
// specific
--topbarbackground: var(--blue);
--panelbackground: var(--blue);
etc...

So we could change general colors, or tweak individual ones. What do you think?

2. I'm not an art guy, I'm having hard times choosing one color over another, or wether this or that should be square or rounded... :) . My work is based on @austin-guevara work. See his mockup [here](https://github.com/yakyak/yakyak/issues/147#issuecomment-195805583). It can (and must) be adjusted, improved, and we should discuss and share ! I will be happy to implement any great and popular idea. UI should be a forever work in progress, and everyone can bring exciting new ideas. I could make it look more apple messages like, we just need someone to draw it, improve it, and I could implement it. As I said, I'm not good at drawing things, I just took someone else design ideas !
As for the top Bar, well, for conv list, it's just a placeholder for now. We could have a search input here later (like in apple messages, or in @austin-guevara mockup), and / or access to general application settings, etc... On the main panel, it reminds current conversation name, and gives access to conversation details and settings. We can make it transparent with blur like apple messages, or add informations / actions, etc...

@matthewdias 
1. I agree with you. material design are only guidelines that we are free to use, adapt, etc... https://www.google.com/design/spec/material-design/introduction.html#introduction-goals

2. I wanted to get rid of osx bar in the first place, and add close / minimize / fullscreen to the top bar. But yakyak is cross platform, and I do not have any windows or linux platform to test it, as we should still bring native platform feeling to those window controls I think. But its high on my list of things to try !

**Comment by algesten** [comment]
I tried your branch, but it seems to have some issues.  

screen shot 2016-04-08 at 21 40 30

warnings for woff2. and then errors whenever i try to switch conversation

**Comment by mrohr** [comment]
if you look at the pull request I had submitted (no hard feelings about reverting!), I ended up abstracting out what constituted a 'theme' into 10~ variables that were much more generic than topbarbackground or panelbackground.  Maybe a middle ground like my previous work had could be the answer?  

 P.S. css vars are pretty cool, hadn't seen them in use before.

**Comment by ariu** [comment]
@mrohr There is no topbarbackground or panel background for now, just very generic variables like you had (see [here](https://github.com/ariu/yakyak/blob/master/src/ui/css/yakyak/colors.less)). But names are not that good, and we could do really more, and maybe a middle ground as you suggested. Please feel free add some change :)

@algesten Will look into it as soon as possible. I already saw the woff2 problem, looks like trifl library is causing this, dont know why yet.

**Comment by austin-guevara** [comment]
@ariu It's really sad to see your amazing work hasn't been adapted to the main project.

**Comment by arnriu** [comment]
@austin-guevara Yes I know, I've been very busy (new exciting job, family stuff...) and didn't find the time to solve the merge conflicts, and work on this. But i'm still around, and I hope I will fix this soon enough ;)

**Comment by davibe** [comment]
@arnriu users want this badly. Just saying.

**Comment by davibe** [comment]
I have checked out this branch and merged-in updates from master (rebasing would have been a nightmare due to mrohr branch being merged and reverted in master)
screenshot 2016-06-10 08 30 45
. I played around a bit.

Updating the branch with master was easy but the way i see it (if i did nothing too wrong) the work is not finished. While some UI things are more appealing some functionalities are missing. I don't see the "controls" bar at the bottom of the user list therefore there is no functionality for muting/closing/starring conversations. Some styles in the conversation are a bit wrong even it some other things are very cool. "Show conversation thumbnails" is broken too. I attach a screenshot here

screenshot 2016-06-10 08 30 45

**Comment by davibe** [comment]
Here are my thoughts

- I think material design does not look too good on desktop because lots of space is wasted.
- The previous theme bent really well with osx and did not look too-bad elsewhere. It's a bit sad for me to loose the osx "integration" feeling.
- In the list of "contacts" i find "timestamp" and "last message" cool at first, but then useless and caotic. Conversation are already sorted by timestamp and i think it's enough
- I love how the user icons bend into the message bubble, expecially when the bubble is more than one line long
- I love that conversation actions have been moved inside the conversation
- I hate the big header below the window titlebar. Maybe we could try metling them together, at least on osx, like this https://github.com/electron/electron/blob/master/docs/api/frameless-window.md
- I hate that big plus(+) floating disk. I don't have a better solution but I could try to make it smaller at first
- I am not sure how i feel about "contact list" group headers with gray background and centered text alignment
- I like how the selected conversation looks in the "contact list" but not how the 'scrollbar' space cuts it out. It actually cuts the entyre contact list. Maybe it should float over it
- Looks like noto font fixes problems we had with emoticons. It seems to me they look pretty neat

Of course these are just my first thought and i am open to other ideas.

I am not sure how to go forward from this PR. Maybe i should push a separate branch to work on then merge it to master once it's ready

**Comment by arnriu** [comment]
So @davibe did you successfully merge ? It would be nice, cause I have no time to rebase, it is hard as you said, lot of things changed.

Original skin discussion is here: https://github.com/yakyak/yakyak/issues/147

I agree with most of your thoughts:

> The previous theme bent really well with osx and did not look too-bad elsewhere. It's a bit sad for me to loose the osx "integration" feeling.

Yeah, but then, what about windows or linux users. Maybe we could have light custom styles for specific os?

> In the list of "contacts" i find "timestamp" and "last message" cool at first, but then useless and caotic. Conversations are already sorted by timestamp and i think it's enough

Maybe we could add this as an option, and toggle it form menu? Like user icons in contact list.

> I hate the big header below the window titlebar. Maybe we could try metling them together, at least on osx, like this https://github.com/electron/electron/blob/master/docs/api/frameless-window.md

Yeah, I already tried it, and it looks pretty nice on mac os. And solves the "big header" feeling. But I had no linux / windows to test so I dropped it for now. But It sure is on my list when i'll have some time for yak yak :)

> I like how the selected conversation looks in the "contact list" but not how the 'scrollbar' space cuts it out. It actually cuts the entyre contact list. Maybe it should float over it

It was like this at some point, but I changed it to what it is now. I can't remember why I did this...


Don't know either what we should do about the PR. For me, if your merge is successfull, its stable right now, and ready to use. I still plan to work on it later on though. There are many improvements to do. Well it's UI / UX, there is always something to improve :)
As for separate branch, I don't know, but we should definitely not wait so long before rebase next time ^^'

**Comment by davibe** [comment]
@ariu or @arnriu in your commit "svg logo" you have delete deploy.sh
Why ?

**Comment by davibe** [comment]
It seems to me we're also missing 
- glup scripts to copy fonts over to the installed app/
- a way to autogenerate the `icon.icns` for the new icon.

Anyway. I have updated a few things on the 'ariu-master' branch of yakyak. @arnriu check them out if you have time :)

**Comment by davibe** [comment]
@ariu or? @arnriu : I would like to add you as a contributor on the readme when i release this. Do you agree ? Which account should I link ?

**Comment by arnriu** [comment]
Hey @davibe , I'll check your updates later today when I have time. Your screenshot looks pretty good :)

If I deleted files, it was a mistake. I'm a front-end web developer, and this was my first steps with electron. I'm not sure what I did with deploy or icons. As for gulp, well, I do not remember why I changed this task.

You sure can add me as a contributor. You can use @arnriu , I will use this account now. Maybe you could ask @austin-guevara too ? He did the design that inspired this PR https://github.com/yakyak/yakyak/issues/147#issuecomment-195805583 , and took part in most discussions about this. Graphics and UI design is half the job in my opinion, and I don't want to take credits for his good contribution.

**Comment by davibe** [comment]
Well @austin-guevara I'll add you too, if you have something against it just tell me. I think i will do v1.3.0

**Comment by austin-guevara** [comment]
Huge props to everyone involved. Thank you for you dedication to making this client better for everyone! I'd certainly like to step up my developer game soon, but I'm so happy I was able to contribute.

**Comment by arnriu** [comment]
@davibe I've made some minor adjustments over yours, how should I upload them?

**Comment by davibe** [comment]
@arnriu i merged into master! I am about to release 1.3.0 

Rebase on master and submit another pull request!

**Comment by arnriu** [comment]
Done :)

**Comment by davibe** [comment]
I am not sure about the `aaa` you made `darkgray`. I need to try it out. When i put #aaa i was trying to give less importance to the timestamp because it's indeed less important than compared to the conversation name. I felt that gray-ing it out made things less caotic. Anyway i will merge this and think about it.

Thank you !

**Comment by arnriu** [comment]
@davibe Yeah, i saw your point, that's why i didn't revert to --lightblack (#455a64) but --darkgrey instead.  #777 is not #aaa I know, but it's still more grayer than before ! My whole points is to have any colors in variables so it's easy for anyone to create a color scheme, and I want to keep as less different colors as possible to make it easy and simple That's why I didn't add a new one for #aaa . If you feel #aaa is better, feel free to add it, but add a new variable for it. ;)

**Comment by davibe** [comment]
i saw it, indeed i removed my comment but you were too fast :P

**Comment by averissimo** [comment]
I haven't experienced any problems but shouldn't woff2 files be added to the paths of fonts?

I find a constant error in the inspector about this. This seems to fix it though: averissimo/yakyak@da405f9

image

**Comment by davibe** [comment]
You're probably right

**Pull request merged**
