### PR TITLE
Use custom window frame for Linux/Windows platforms

### PR DESCRIPTION
**Pull request by Sazpaimon**
This is my attempt at fixing #211. Here's how it looks on Windows/Linux:

image

Clicking the hamburger will bring up the application menu as a context menu rather than as a separate row altogether.

I had to use SVG images from https://github.com/Templarian/MaterialDesign for the minimize/maximize/restore/close icons since Google doesn't include those in its font set. If you prefer a different way of integrating these icons, let me know.

This is my first time working in Electron so feedback is appreciated.

### CODE REVIEW

**Comment by davibe** [comment]
I tested on mac and brifly on windows. I hope linux is fine. I think i will include this in 1.4.3. Thank you for your great contribution.

Just 2 comments for the next time
- i don't like code lines starting with `,`
- i prefer spaces before `{` in css

**Comment by Sazpaimon** [comment]
Thanks! I also don't like leading commas and no space before `{` but I was following existing convention. I'll keep it in mind next time.

**Comment by nerijus** [comment]
Using Window Maker on Linux it is OK:
screenshot-20170415_105338
But on MATE the window has no borders:
ekrano kopija 2017-04-15 10-55-41

**Comment by nerijus** [comment]
I see it fixes issue 211 by hiding window borders. Is it possible to have an option which when selected would not hide the borders?

**Comment by Sazpaimon** [comment]
If it makes more sense to keep the window frame on Linux, that can certainly be arranged.

Out of curiosity, how does [Discord](https://discordapp.com/apps) look on your setup? That was what I was trying to emulate here.

**Comment by nerijus** [comment]
I don't have an account, without logging in it looks like this:
ekrano kopija 2017-04-15 17-44-11

**Comment by nerijus** [comment]
Yakyak screenshot on another PC (MATE) - as you see, both left and bottom have no borders and is indistinguishable from the browser window below:
 
ekrano kopija 2017-04-15 17-50-46

**Comment by Sazpaimon** [comment]
Okay, I think it makes sense to show the window border on Linux since there's no telling how a window manager will render a window. I'll make another PR to fix that.

**Pull request merged**
