### PR TITLE
Fix bad initials / avatars in convlist and convadd

### PR DESCRIPTION
**Pull request by averissimo**
This is mostly an implementation update.

user's avatars were being generated in 3 different methods, this unifies it by using `drawAvatar` from util.coffee

### CODE REVIEW

**Comment by davibe** [comment]
conflicts!

**Comment by averissimo** [comment]
fixed!

**Comment by davibe** [comment]
no :P

**Comment by averissimo** [comment]
it was a bad idea to correct indentation and break some code in multiple lines -_-

should be ok

**Pull request merged**
