### PR TITLE
Re-add retina tray icon

### PR DESCRIPTION
**Pull request by monchote**
I added this for the yak icon and it got lost when the new icon got reintroduced. 

This is different from #320

### CODE REVIEW

**Comment by monchote** [comment]
@davibe Merge conflict resolved.

**Comment by davibe** [comment]
@monchote is this still relevant after https://github.com/yakyak/yakyak/pull/362 ?

**Comment by monchote** [comment]
@davibe Yes, we still need this as the other menu icon with retina versions is only for macOS. This is the one shown in Linux and Windows(?) which also support hi-dpi screen these days.

**Comment by davibe** [comment]
thank you

**Pull request merged**
