### PR TITLE
Fix login.coffee

### PR DESCRIPTION
**Pull request by ryantiger658**
Fixing the startup loop. 

However, after login I am hanging on `One moment please...` message with no obvious errors in the log. It seems to be related to the URL that we get back from Google, but I can't tell for sure. 

See https://github.com/yakyak/yakyak/issues/1095#issuecomment-578852932

### CODE REVIEW

**Comment by averissimo** [comment]
Do you still have this on the v1.5.4-beta-rolling? *(downloaded in the last day)*

This should be fixed with a more recent version of Electron *(which, in turn uses a different user agent)*

**Comment by averissimo** [comment]
Nevermind, I read your post in the "No new releases" issue

**Comment by ryantiger658** [comment]
Yes I was having it on v1.5.4-beta-rolling as of 10am this morning. If I was reading it right that release is built off of master and master has the broken code.

**Comment by averissimo** [comment]
Ok, I was under the impression that it was solved with an update to electron, but I was completely wrong.

Seems like Google doesn't like the default user-agent and finds it unsecure.

I manually merged your commit, I'm closing the issue.

**Comment by averissimo** [comment]
Thanks!

**Comment by averissimo** [comment]
There's still a problem with the cookie not being retrieved.

Once I login it doesn't close the window and proceeds to open yakyak.

Working on it now

**Pull request merged**
