### PR TITLE
Fix crash when starting a new conversation - fixes #1241.

### LINKED ISSUE #1241: Yakyak crashes when starting new conversation
When i try to start a conversation with someone that isn't in de coversations list the app crashes, with the following error message;  https://www.dropbox.com/s/hrr7txakd5s7qjd/Schermafbeelding%202020-09-22%20om%2009.27.29.png?dl=0

currently using: yakyak v1.5.10 on MacOS 10.15.5

### PR DESCRIPTION
**Pull request by HomerSp**

### CODE REVIEW

**Comment by averissimo** [comment]
@homersp do you want to became a maintainer of Yakyak? _(at least to be able to merge pull requests)_

Life got in the way and I'm not consistent on looking over yakyak.

**Comment by HomerSp** [comment]
> @HomerSp do you want to became a maintainer of Yakyak? _(at least to be able to merge pull requests)_
> 
> Life got in the way and I'm not consistent on looking over yakyak.

I definitely can, but to be honest I'm not sure how much time I want to spend on it - it feels like Google are more and more deprecating the old hangouts in favour of hangouts chat. I am still using yakyak daily though, so if I'm able to merge PRs I can at least do fixes as they pop up without having to bother you.

**Comment by averissimo** [comment]
Yeah, the code is pretty stable by now, the only enemy is Google itself.

Please be on the look out for any of my changes in this version. I updated some packages and removed some deprecated ones.

@davibe can you add @HomerSp to the Yakyak team?

**Comment by averissimo** [comment]
@HomerSp I've just tried to contact @davibe via a different form of communication, hopefully everything is alright with him and he just doesn't use hangouts anymore

**Comment by HomerSp** [comment]
@averissimo Thanks, I can see he's still active on github, so it's probably that he just doesn't use hangouts anymore.

**Comment by averissimo** [comment]
You're now on the team and have write permissions, take good care of the code :-)

Thanks @davibe

I'll still try to contribute as I can. I've added some information on the wiki on how we release versions _(a tag will trigger a build in travis that create/updates a release with new binaries)_.

I've used the rolling beta release instead of beta1, beta2, beta3... but don't feel obligated to follow that. It was purely to keep that page clean.

I would just ask you to keep pushing changes via pull requests, as that allows for a better tracking of changes.

**Comment by averissimo** [comment]
I'm not familiar as to why, maybe you are:

Node v14 must be used instead of v15 as this version does not build the binaries, so `.travis.yml` has been changed to v14 instead of latest

**Comment by HomerSp** [comment]
Thanks for the information, I was actually wondering how new releases were deployed! I'll probably keep the rolling releases as that feels like a better fit for a project like this that won't be updated too often. And yeah, I'll keep doing PRs - the automatic travis builds can be quite helpful in tracking down problems in case you forget to run npm test or the like (which I did today, hah).

I haven't looked into why node v15 fails, but I'll do that and hopefully figure out what's going on.

**Comment by HomerSp** [comment]
@averissimo I've had a look now, and the node v15 problem looks to be this: https://github.com/electron/asar/issues/210 - that's what electron-packager uses to generate the asar file. It doesn't actually hang for me though instead it just stops. This seems to be a nodejs issue, and not asar though, so I think we'll have to stick with the older version for a while yet.

**Comment by averissimo** [comment]
Wow, nice digging!

I wasn't that concerned as v14 is still recent _(and still supported_) and thought that's some information I should pass to you.

If you have any question about the infrastructure of yakyak I'll be more than happy to help if I know the answer or try to find out.

About the code you already proved more than capable and knowledgeable. Hats off to you.

**Pull request merged**
