### PR TITLE
Enable spellchecker

### LINKED ISSUE #61: Spell check as you type

### PR DESCRIPTION
**Pull request by monchote**
Only works for the system language and underlines misspelled words. It doesn't offer suggestions at the moment.

Fixes #61

### CODE REVIEW

**Comment by monchote** [comment]
Possible improvements:
- Use macOS's builtin multi-language spellchecker (I'm still trying to figure this out, see: https://github.com/nylas/N1/issues/1392)
- Ability to change language globally (also per conversation?)
- Ability to turn it off

**Comment by davibe** [comment]
I merged but i think i will have to revert. This is what i get on osx

screenshot 2016-06-26 10 07 05

**Comment by davibe** [comment]
reverted here https://github.com/yakyak/yakyak/commit/53e1754b545e5f8757f41d66c79f3efd2297faf1

**Comment by monchote** [comment]
Hey @davibe, thanks for checking. I'm also in macOS, did you run the following?
```
rm -fr node_modules/
npm install
```

These are the npm and node versions I'm running:
```
(spellchecker) $ npm -v
3.9.5
yakyak (spellchecker) $ node -v
v6.2.2
```

**Comment by monchote** [comment]
See https://github.com/electron-userland/electron-builder/issues/453

**Pull request merged**
