### PR TITLE
 support RTL in the input area

### PR DESCRIPTION
**Pull request by chaim-chv**
this simple line will add the optin of RTL: if you start to write in the text box in RTL kanguage, the text automatic go to the right side.

### CODE REVIEW

**Comment by averissimo** [comment]
There was 2 problems with the code you suggested. I've corrected it in master

Can you test it out to see if it works fine?

**Comment by chaim-chv** [comment]
i cant test it
i test in my computer, on my yakyak (windows) and in accordance change things here
if you can make release of the current version, in exe who support windows, i can test it.
thank you! this program so helpful!

**Comment by averissimo** [comment]
version 1.5.5 has been updated in releases, please test it.

**Comment by chaim-chv** [comment]
one of the features works fine
but the second fail
i will fix it right now

**Pull request merged**
