### PR TITLE
'Help -> About' window

### PR DESCRIPTION
**Pull request by averissimo**
Shows a menu entry and about window that has the following information:

It follows the same logic when building the layout as the main window
- Version number
- License
- Main authors
- Contributors
- Link to github.com/yakyak

Additionally if there is a newer version, then it is shown a message in this window

image

version.coffee was changed to follow 4 spaces tab indentation and added an noAlert argument, which checks for newer versions, but without showing an alert.

_note:_ to prevent lingering processes, both the main and about window are explicitly destroyed.

### CODE REVIEW

**Comment by averissimo** [comment]
@jessejoe can you try to replace file `YakYak.app/Contents/Resources/app/ui/views/aboutlayout.js` with 

aboutlayout.js [gist](https://gist.github.com/averissimo/3a05552d89df809a15f50974dd89e4d4#file-aboutlayout-js) | [direct link to raw file here](https://gist.githubusercontent.com/averissimo/3a05552d89df809a15f50974dd89e4d4/raw/3aaa0687df58ed456406429e00f2a7878c1c62d7/aboutlayout.js)

**Comment by jessejoe** [comment]
@averissimo that did it! YakYak loaded **AND** images are there!

**Comment by nerijus** [comment]
@averissimo, where do I find About menu on Linux?

**Comment by averissimo** [comment]
Under the new 'Help' menu (it's new)

**Comment by averissimo** [comment]
@nerijus Under the new 'Help' menu (it's new)

**Comment by nerijus** [comment]
I don't see Help menu. I am using the latest yakyak git.
screenshot-20161129_142227

**Comment by averissimo** [comment]
You need to merge my averissimo/yakyak#1.4.0-beta3 branch

Or just add a `!` in line 389 of menu.coffee before isDarwin

Rookie mistake lol

**Comment by nerijus** [comment]
The latest yakyak git is OK, I see Help menu.

**Comment by averissimo** [comment]
davibe is on a roll!! LoL

**Pull request merged**
