### PR TITLE
Add 'Show image preview' feature #620

### PR DESCRIPTION
**Pull request by AlessSala**
Available in Menu->View->Show image preview .
It is possible to toggle the image preview with
CTRL+P keyboard combination.

This feature tries to cover [this request](https://github.com/yakyak/yakyak/issues/620) .

### CODE REVIEW

**Comment by averissimo** [comment]
I've just sent an image and disabled the option, but it still shows the preview

image

**Comment by AlessSala** [comment]
It hides previews from sent urls, such as twitter or instagram. The images directly sent are another story :P.
Lemme see if i can manage it.

**Comment by averissimo** [comment]
Ooopsie.. do you think it makes sense to also hide images like those? I'd say so, but I can go with whatever you decide

**Comment by AlessSala** [comment]
I'll try to handle it tomorrow, somehow :)
It's my first time with coffeescript, you know.

**Comment by averissimo** [comment]
You're doing a great job with it!

**Comment by averissimo** [comment]
I'm merging it as it is, it is something uses will like a lot.

If you wish to add to it, please create another pull request with the changes and I'll merge it too!

Thanks a million!

----

About the translation, what's different?

*(btw, love the country, beautiful and incredible climbing!)*

**Pull request merged**
