### PR TITLE
dark theme implementation /w theming framework

### PR DESCRIPTION
**Pull request by mrohr**
I wanted a dark theme, so i forked and created one.  In the process I wanted it to be more extendable, so I've set up a theming system.  I abstracted out any css coloring to a set of less variables in src/ui/css/themes/core.less, without any actual variable definitions. 

 A theme is defined by creating a *-theme.less file in the themes directory that defines the theme variables and imports the core.less file at the bottom of the file.  A separate less-themes task builds every *-theme.css file and makes them available to the application.  Themes also need to be added to the new Themes submenu in Menu.

### CODE REVIEW

**Comment by mrohr** [comment]
The actual dark theme implementation is based off the colors in the new Hipchat dark theme which I found pretty aesthetically pleasing.

**Comment by stygiansabyss** [comment]
Any chance of this getting some love?

**Comment by KruyKaze** [comment]
Sorry to hijack this thread but I searched and found no info on how to change themes. Can someone tell me how?
I'm using  yakyak 1.3.0-2 from here : https://aur.archlinux.org/packages/yakyak/

**Comment by davibe** [comment]
That version does not have 'theme switching' enabled. It was enabled only for macs. Pre-release 1.3.1 you can download from github has it.

**Comment by billchase2** [comment]
Any chance of getting the dark mode to change automatically with the OS's dark mode? My Mac switches to dark mode at sunset and I'd like for this app to change along with it.

**Pull request merged**
