### PR TITLE
Add telugu translation

### PR DESCRIPTION
**Pull request by sriharshachilakapati**

### CODE REVIEW

**Comment by averissimo** [comment]
Thanks a lot, it will be available in the v1.5.4 version that will be released in a couple of hours

**Comment by sriharshachilakapati** [comment]
@averissimo I just noticed that PR #851 added new strings to translate. I'd like to update that as well. Can you make sure to ping me after you've prepared to release? That makes it easier for me to see all the missing strings and translate them.

**Comment by averissimo** [comment]
Ok. I'll let you know here

**Comment by sriharshachilakapati** [comment]
@averissimo I saw that you have bumped the version. Should I update this now? I can give a new PR in an hour.

**Comment by averissimo** [comment]
Yes.

**Comment by sriharshachilakapati** [comment]
@averissimo Sorry for the delay. Created #1110 after adding all missing translations.

**Pull request merged**
