### PR TITLE
 setpresence with each connection cycle

### PR DESCRIPTION
**Pull request by averissimo**
#167 original issue
#571 failed attempt to solve it

### CODE REVIEW

**Comment by averissimo** [comment]
@NvrBst @veasnalkj I believe this is fixed with this pull request

But as my tests have failed before (lol) I would like to ask you guys to test it, in the release v1.4.2-setpresence release in my fork

https://github.com/averissimo/yakyak/releases/tag/v1.4.2-setpresence

------------

My tests:

image

image

**Comment by veasnalkj** [comment]
Great!  Just tried it.  It does show online in the messaging/hangout window on the Gmail page.  For people using other chat clients, like Pidgin and Adium, it still shows offline.  
Thanks,
Lucas

**Comment by NvrBst** [comment]
Heyas; Yup looks good to me. After an hour it still shows as Online in Hangouts Web App, and the Gmail Web App. I do not use the 3rd party apps like mentioned above, so I haven't tested those, but at least the Official Apps see you as online now. :) Good work!

I still see YakYak showing most people as "Online" when they are indeed not online in the Offical App though. So that's still a bug.

**Comment by averissimo** [comment]
@veasnalkj 

I can't connect to google hangouts using pidgin, it seems that since the Hangouts switch that it does no longer support gtalk

Can you show me how to connect?

image

https://support.google.com/a/answer/49147?hl=en

**Comment by averissimo** [comment]
@NvrBst that should be connected with latest build of the v1.4.2 _(prerelease)_

**Comment by NvrBst** [comment]
Yup yup, fix in the new release! Thanks! :) all good now.

**Comment by averissimo** [comment]
Noticed that my comment was very baddly written :)

I was refering to a newer commit that fixes:

> I still see YakYak showing most people as "Online" when they are indeed not online in the Offical App though. So that's still a bug.

**Comment by veasnalkj** [comment]
Hmmmm… May not be so easy.  I work for a university and we use Google for our email for staff and students and as such I’m using an enterprise account for which Google still does support XMPP.   Looks like the standard google.com <http://google.com/> accounts do not.  May not be worth pursuing, particularly if you’re not able to connect that way.
Thanks,
Lucas

**Pull request merged**
