### PR TITLE
Enable spellchecker

### LINKED ISSUE #61: Spell check as you type

### PR DESCRIPTION
**Pull request by monchote**
Highlights misspelled words but doesn't offer suggestions at the moment.

Fixes #61
Relates to #271

### CODE REVIEW

**Comment by monchote** [comment]
Make sure to clean the node modules before compiling and running:
```
rm -fr node_modules/
npm install
```

**Comment by davibe** [comment]
ok i try again

**Comment by davibe** [comment]
I am still getting the same error

**Comment by monchote** [comment]
@davibe What version of node do you have?

**Comment by davibe** [comment]
4.4 but i think node has little to do with this

**Comment by davibe** [comment]
dade@choo:~/work/yakyak(master)$ node -v
v4.4.4

**Comment by monchote** [comment]
I'm on v6.2.2 and not getting that error.

What do you suspect it can be?

**Comment by davibe** [comment]
I have no idea. Maybe the module is built with a node-gyp version that is different from the electron one

https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

**Comment by davibe** [comment]
I have reverted the merge using the --hard way. I hope nobody pulled this in the mean time

**Comment by monchote** [comment]
@davibe I've just tested it on 2 more dev environments and works just fine so I suspect the problem is there's something different in our node/npm setups.

More than happy to help you figure out what it is as I think this feature is incredibly important.

See screenshot attached of it working.
screen shot 2016-06-27 at 10 51 37

**Comment by davibe** [comment]
I understand. I don't have time at the moment. If it was something i could just merge and go then ok. Otherwise i will have to check with more calm. 

I am also thinking that since i build the windows/linux binaries on osx a native module will have similar problems on other platforms ...

**Comment by monchote** [comment]
@davibe [node-spellchecker](https://github.com/atom/node-spellchecker) works with Windows, macOS and Linux (via Hunspell). I'm installing VMs to test it thoroughly in Linux and Windows now.

**Comment by davibe** [comment]
I know it works as a npm package. But if it's BUILT on mac it may not work on other os

**Comment by monchote** [comment]
Oh, I see what you mean. I'll test it and report back.

**Comment by monchote** [comment]
@davibe So the binaries built from mac don't work on Windows or Linux. Managed to build from Linux and the spellchecker works. Building from Windows is a total nightmare.

**Comment by davibe** [comment]
yesterday i tried looking for `npm search spellchecker` and I think there may be some other alternative that does not require native building. Some of them are specifically targeting electron. No idea which one actually works though.

**Comment by monchote** [comment]
@davibe Thanks, I'll keep looking into it when I have more time. Shall we reopen #61 in the meantime?

**Pull request merged**
