### PR TITLE
Docker branch cleanup

### PR DESCRIPTION
**Pull request by averissimo**
__Does this make sense?__

The idea is to either build from master in github _(default in case `$TAG` is not set)_ or a given tag

`$ TAG=1.4.1 docker-compose up`

or

`$ TAG=i18n docker-compose start`

or for github master's

`docker-compose up`

should the command be a script instead? _(as it is too long)_

### CODE REVIEW

**Comment by davibe** [comment]
i am doing something similar locally. Take a look at the `dade` branch. My branch adds some files i use to build on macosx. I feel like it's not refined yet but it has been working fine.

**Comment by averissimo** [comment]
I forgot to pull latest `dade` :)

For building you are first merging the `master` branch to `dade`, right?

**Comment by davibe** [comment]
before building i usually rebase dade on master, that's why i don't suggest you to use the branch `dade` for anything other than reading it.

Basically i do
```
git chekout master
git pull --rebase
git push
git checkout dade
git rebase master
git push --force
```

**Comment by averissimo** [comment]
ok, cool.. I'll close this!

**Pull request closed without merging**
