### PR TITLE
Feature/google voice sms

### PR DESCRIPTION
**Pull request by hawksprite**
This adds the capability for users to use yakyak while also wanting to send google voice SMS through a related hangouts conversation.

Internally the current YakYak setup is to always use the BABEL delivery method.  When you attempt to post a message to hangouts in a conversation that is using GOOGLE_VOICE it fails.  This adds a toggle option in the context menu as a way for user's to change the default behaviour of the library's delivery method.

NOTE:  This is probably seen as a "quick fix" for the issue, a full fix would be automatically detecting the delivery method for each conversation at a lower level.

Also, for Google Voice users setting the delivery method to GOOGLE_VOICE doesn't make BABEL conversations fail to send for some reason.  So this is more of a check it if you're mostly a google voice user.

### CODE REVIEW

**Comment by averissimo** [comment]
Following  #90 discussion:

- What was appearing before the question mark?
- Was sending an image/mms working before?

**Comment by averissimo** [comment]
We need some information from an google voice conversation.

We just released a new v1.4.4-google-voice binary

Can someone open Yakyak and:

- Open a google voice conversation
- Press Ctrl + Alt + i to open the developer pane
- Open the Console tab 
- Expand the last conversation / outer / inner and screenshot it  as the picture below shows

This should not reveal any unique id or something to compromise privacy, if it appears please censor it :)

screenshot from 2017-09-14 18-40-55

**Comment by natecox** [comment]
image

**Comment by averissimo** [comment]
great, so it's possible to get the delivery medium from the conversation itself :)

Working with this will avoid having a global option,

@hawksprite hope you don't mind if I change a couple of things in your code :)

An implementation in the library would be better, but due to the asynchronous nature of the library, it might be best to manage this in yakyak

**Comment by hawksprite** [comment]
I agree, feel free!  This pull was meant more as a way to outline the core issue with the google voice delivery.

**Comment by averissimo** [comment]
@natecox 

- What was appearing before the question mark?
- Was sending an image/mms working before?

__Can you compile yakyak from source?__

I've adapted the code in the branch hawksprite-feature/google-voice-sms to detect the delivery medium and use it, instead of using a global option. 

I'd like if someone test it? _(currently only for text sms.. for images it fallbacks to as it is in normal releases)_

**Comment by chazz422** [comment]
I've never had the google voice SMS icons working.  Always a question mark for me.  I only get icons for hangout messages.  Also, I don't get names, only phone numbers for SMS.

As for image/mms, I haven't tried it through SMS.  I only send images to hangouts users.

**Comment by natecox** [comment]
@averissimo The icons have never worked for me on YakYak, I've always seen them as `?`. Same with image sending, although that's not something I do often anyways.

**Comment by averissimo** [comment]
Ok, cool I just don't want to break functionality with this new code, so I was making sure :)

The binaries are being built for you guys to test if __sending text__ to google contacts works out of the box _(without any global option)_

Can you guys test: https://github.com/averissimo/yakyak/releases/tag/v1.4.4-google-voice-av

**Comment by chazz422** [comment]
Global menu option is still there.  Is that how it is expected to be?

**Comment by averissimo** [comment]
Forgot to delete it :) but that was no longer used for the actual sending of messages

anyway, a new version at that link should be available without that option and some leftover ui code

Can you give feedback on it?

**Comment by chazz422** [comment]
Yes, it's working without the global option checked.

**Comment by averissimo** [comment]
Ok, keep testing it in your day to day :)

I'll prepare the merge as this requires the base library to also be updated

**Comment by chazz422** [comment]
Will do.  By the way, I'm running on Linux, but don't think that should
matter for this type of change.  I have a windows machine at home that I
can try it on later.

**Comment by averissimo** [comment]
@hawksprite do you want to merge the yakyak/hawksprite-feature/google-voice-sms branch?

or I can create a new pull request and change this?

This is basically the same so if you don't say anything by the time hangupsjs library is updated I'll do the latter

**Comment by averissimo** [comment]
@chazz422 it should not, but the more widely tested this is the better :) so we don't have any surprises ;)

**Comment by nsubtil** [comment]
The binaries from https://github.com/averissimo/yakyak/releases/tag/v1.4.4-google-voice-av seem to work for me --- GV messages now get sent correctly.

**Comment by averissimo** [comment]
@nsubtil great! thanks for testing

This will be merged and released soon

**Comment by lazyb5** [comment]
Are you guys going to try and get contact names instead of just showing the phone number? Like the chrome hangout extension.

**Comment by averissimo** [comment]
Going to merge branch where newer work was done.

For more information see newer pull request that I'll create in a moment

**Comment by averissimo** [comment]
Can someone test pre-release v1.4.4 ? it should implement all the changes discussed in this pull request correctly.

We are driving for a new main release after testing this one out :)

Cheers and thanks again for the feedback and contributions!

**Comment by plessbd** [comment]
This new version allows me to send messages to my sms contacts via project fi!

So from my testing this works wonderfully

**Comment by lazyb5** [comment]
I'm using hangouts with google voice and contact names still aren't sync. It just shows the phone number. The chrome extension shows contact names.

**Comment by averissimo** [comment]
@lazyb5  that is not covered in this new feature in yakyak :\

The data we get from hangouts is just the phone number that is shown.

Something else must be done to obtain the contact names, you can check out some discussion on this on #232

**Comment by lazyb5** [comment]
@averissimo OK thanks, I'll keep checking to see if any progress is made. Thanks to all the devs this is a great program. I would use over the extension if I wasn't a voice sms user.

**Comment by chazz422** [comment]
I've installed v1.5.0 and have a couple problems that were not in 1.4.3.

On the windows platform, the delete conversation option for SMS messages is not working.  They just stay there as if nothing happened.

On the Linux platform, deletion works fine, but when a new SMS arrives that was previously deleted, it will crash yakyak.  If I leave the SMS without deleting it, then new messages will not cause the crash.

Not sure why it behaves so differently on each platform but hopefully you can reproduce this.

**Comment by averissimo** [comment]
I don't use sms so it's difficult to reproduce, is this something that only happens to sms conversations or also occurs with normal hangouts?

Can you run yakyak from the command line and check if some exception appears?

**Comment by chazz422** [comment]
@averissimo I usually don't delete hangouts, only sms, but I tried, just now, to delete an old hangout and it wont delete in windows.  So it appears the problem is not isolated to just SMS.

**Comment by averissimo** [comment]
what do you mean deleting and hangout/sms.. is it going to "details" -> "delete conversation"

or something else?

Trying to reproduce on linux and it works

**Comment by chazz422** [comment]
yes, deleting from the "details" -> "delete conversation".  Regardless of if it originated from google voice sms or native hangouts messaging, the conversation will not disappear on windows.

The "delete conversation" is working fine on linux, but if I receive a new voice SMS, it will crash the client.  For example, amazon will send me a SMS from +1262966 and it will crash when I click to view it.  After restarting the client, I can click and view the message without a problem.  As long as I don't delete the message, I can receive new ones.  But if I delete it and then receive another one, it will crash again.  I'll get you the details of the crash from the command line like you requested but I have to wait til I get another one.  I don't do much with SMS besides amazon notifications and my bank (which also has the same problem).  Just to reiterate, this crashing is only on linux version, not windows.

So 2 separate problems here, but don't know if there's any relation.  Neither of these problems existed in 1.4.3.

**Comment by averissimo** [comment]
Can you run yakyak from the command line and report which exception appears?

**Comment by chazz422** [comment]
I ran it from the command line and left the terminal open to monitor for exceptions.  I received a SMS for amazon delivery today and it didn't crash.  So the problem's not happening.  I'm going to try running it with nohup to capture tty output to a log.  I'll do some more troubleshooting as I can and let you know what I find.

**Comment by averissimo** [comment]
Classic!! if so please open a new issue :)

**Pull request closed without merging**
