### PR TITLE
Feature me message

### PR DESCRIPTION
**Pull request by bseber**
* rendering `/me` messages works \o/
* but sending `/me` actions depends on https://github.com/yakyak/hangupsjs/pull/49

imho, it doesn't make sense to have a rendering feature only. So we have to wait for hangupsjs release I think.

### CODE REVIEW

**Comment by davibe** [comment]
travis ci build fails (?)

**Comment by bseber** [comment]
@davibe I've not fixed it yet since this feature cannot be used without a new hangupsjs release.

**Comment by davibe** [comment]
i believe @algesten wants to embed hangupjs source code in yakyak at some point. But ok, let's wait for him to answer

**Comment by bseber** [comment]
just rebased on master. however, one unit test still fails (hangupsjs dependency)

@davibe @algesten actually i appreciate the separation of yakyak and hangupsjs.
yakyak is the ui client and hangupsjs the api abstraction for hangouts.

**Comment by davibe** [comment]
I did not understand correctly before. Martin (algesten) moved the repository under the yakyak github group. Basically he's loosing interest in the project so we will have to maintain the lib as best as we can.

This means I am free to merge your pull request and i will do it as soon as i can so you can complete this PR too

**Comment by davibe** [comment]
I merged your stuff in hangupsjs so you can go on

**Comment by bseber** [comment]
yay, thanks :)

**Pull request merged**
