### PR TITLE
setpresence with each connection cycle #167

### PR DESCRIPTION
**Pull request by averissimo**
Sets presence every time there is a connection event (and is connected)

#167

### CODE REVIEW

**Comment by davibe** [comment]
does it make sense to do it periodically ? like every minute if you're connected.

**Comment by averissimo** [comment]
It takes around 30mins timeout, so every minute might be overkill. Attaching this to the handle `update:connection` seemed logical, but so does doing it periodically, I don't really favor one or the other.

You know the inner ways of YakYak better than me and whichever way seems better to you I can implement it :)

**Comment by davibe** [comment]
lets start with this.

**Comment by NvrBst** [comment]
Heya!

I'm still seeing this issue. I have upgraded to the latest pre-release (v1.4.2 - 9ade528) released 1 day ago.  I confirmed the change you made to set the presence on every _"update:connection"_ is in the code on my system:
```
ui/source/controller.js
      if (connection.state === connection.CONNECTED) {
        later(function() {
          return action('lastActivity');
        });
```
I deleted all the other YakYak's on my system, and ran this one. However, when I leave YakYak in the "Closed to Tray" state, my online status is set to Offline after a while. I have timed how long this takes, by moving my mouse around the YakYak client, then closing it to tray and seeing when it sets me to offline. It does it in exactly 15 minutes and 10 seconds. You have to log in and out of hangouts web interface to have the client refresh the online status of the list quicker. Else the web client doesn't update the people's status as often unless you relog in.

How often does this _"update:connection"_ happen in a _"connection.CONNECTED"_ state? Can the connection state be changed from "CONNECTED" to something other after a while? i.e. "IDLE" or "CLOSED" if no activity has been detected for awhile? Then it stops setting the presence? Maybe it doesn't go into this state every 15 mins?

Maybe setting _lastActivity_ periodically may be better? Every 10-minutes to stay within the 15-minute window?

**Comment by averissimo** [comment]
The update:connection should be performed every minute or so, but I'm testing it right now to make sure. In 20 mins I'll send a new screenshot

image

What I'm seening is a huge difference on who is online between YakYak and gmail hangouts interface. That should be a new bug :(

**Comment by averissimo** [comment]
The timer in `connection.coffee` is not being run with the hidden window keeping the connection active.

Just confirmed that with the inspector window open it works. I probably had that open during the tests :\

**Comment by NvrBst** [comment]
Yea, running 1.4.2, I see that YakYak is getting confused on who is online and not. It says almost everyone is online. So some bug there in the new version. :)

Ah good to know you found the issue with the _presence_. :) Need to find a different place to update _presence_ then it sounds like. :P

**Comment by averissimo** [comment]
I think associating it to the noop event from hangouts might be the way to go.

Why? it is a keep alive signal, so doing it after receiving is obvious

Problem is that it does keep the status as available... need to work on this more

**Comment by averissimo** [comment]
let's move the conversation to #596 :)

**Pull request merged**
